### PR TITLE
Make HyperJAXB3 compilable under JDK 1.8 and Apache Maven >=3.3.*

### LINKED ISSUE #35: Cannot compile on mvn 3.3.9 and JDK 1.8
I tried to compile with:
```
zangetsu@ares ~/proj/coreso/hyperjaxb3 $ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/share/maven-bin-3.3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /opt/oracle-jdk-bin-1.8.0.144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.12.4-gentoo", arch: "amd64", family: "unix"
```

First error was to plugin not following Maven plugin naming convention, so I renamed the plugin to **hyperjaxb3-maven-plugin**

Then I tried to compile with result:
```
INFO] Hyperjaxb3 ......................................... SUCCESS [  0.587 s]
[INFO] Hyperjaxb3 EJB ..................................... SUCCESS [  0.018 s]
[INFO] Hyperjaxb3 EJB Schemas ............................. SUCCESS [  0.021 s]
[INFO] Hyperjaxb3 EJB Schemas Persistence ................. SUCCESS [  4.599 s]
[INFO] Hyperjaxb3 EJB Schemas Customizations .............. SUCCESS [  2.022 s]
[INFO] Hyperjaxb3 EJB Runtime ............................. SUCCESS [  1.260 s]
[INFO] Hyperjaxb3 EJB Roundtrip ........................... SUCCESS [  3.586 s]
[INFO] Hyperjaxb3 EJB Plugin .............................. SUCCESS [  2.505 s]
[INFO] Hyperjaxb3 EJB Extensions .......................... SUCCESS [  0.007 s]
[INFO] Hyperjaxb3 EJB Extensions Naming ................... SUCCESS [  0.011 s]
[INFO] Hyperjaxb3 EJB Extensions Naming [custom-naming-pre_0_6_0] SUCCESS [  0.137 s]
[INFO] Hyperjaxb3 Maven ................................... SUCCESS [  0.021 s]
[INFO] Hyperjaxb3 Maven Plugin ............................ FAILURE [  2.011 s]
[INFO] Hyperjaxb3 Maven Plugin Testing .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.114 s
[INFO] Finished at: 2017-08-29T10:37:53+02:00
[INFO] Final Memory: 41M/742M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.2:helpmojo (help-goal) on project hyperjaxb3-maven-plugin: Execution help-goal of goal org.apache.maven.plugins:maven-plugin-plugin:3.2:helpmojo failed: 21774 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hyperjaxb3-maven-plugin
```
Not much to see, but I just upgraded maven-plugin-plugin to version 3.5 and I can compile now. This is probably related to 1.8 JDK, but cannot confirm....

### PR DESCRIPTION
**Pull request by archenroot**
fixes #35

### CODE REVIEW

**Comment by bgedik** [comment]
What does it take to have 0.6.3 on maven central repo?

**Comment by highsource** [comment]
Release is quite easy, but I'm not sure tests run well.

**Comment by bgedik** [comment]
I would like to have the 0.6.2 release in maven. Can you point me to failing tests, if there are any? If there is something I can fix, I'll help.

**Comment by highsource** [comment]
`mvn clean install -Pall` in `ejb/tests`, but not all of them should work actually. I think it's fine to release 0.6.2.

**Comment by bgedik** [comment]
These failures seem unexpected:
* Samples: 
  * ``po-initial``
  * ``po-customized-toplink``
  * ``uniprot``
  * ``customerservice-cxf``
* Tests:
  * ``edxl``
* Tutorials:
  * ``po:step-one``

Any particular ones you think should be passing? 

These failures seem expected, as I see the following message in the pom file: ``<!-- Remaining failing projects including to be able to update versions -->``
* ``ccr``
* ``cda``
* ``component``
* ``custom-naming``
* ``customType``
* ``customizations``
* ``dl``
* ``fpml-pretrade``
* ``ims-eportfolio``
* ``ims-lip``
* ``nml``
* ``plmxml``
* ``po-mysql``
* ``rim``
* ``sml``
* ``star``

**Comment by highsource** [comment]
@bgedik Here you go:

https://github.com/highsource/hyperjaxb3/releases/tag/0.6.2

Also released to Maven Central (will appear there in few hours).

**Comment by bgedik** [comment]
Thanks @highsource

**Comment by archenroot** [comment]
Good stuff.

**Pull request merged**
